name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Linux
      run: go build -v -o planning-poker-importer_linux ./...
      env:
        GOOS: linux
    - name: Build Darwin
      run: go build -v -o planning-poker-importer_darwin ./...
      env:
        GOOS: darwin
    - name: Upload
      uses: actions/upload-artifact@v2.2.4
      with:
        name: planning-poker-importer*
        path: .
